[package]
name = "enigmagen-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
enigma-simulator = "^1.3"
genevo = "^0.7"
moka = { version = "^0.12", features = ["sync"] }
chrono = "^0.4"
rand = "^0.8"
anyhow = "^1.0"

[dev-dependencies]
approx = "^0.5"
